src/Entity/Facture.php
<?php

namespace App\Entity;

use App\Repository\FactureRepository;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\ORM\Mapping\HasLifecycleCallbacks;

#[HasLifecycleCallbacks]
#[ORM\Entity(repositoryClass: FactureRepository::class)]
class Facture
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $client = null;

    #[ORM\Column(length: 255)]
    private ?string $reservation = null;

    #[ORM\Column()]
    private ?float $priceHT = null;

    #[ORM\Column()]
    private ?float $PriceTTC = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;


    #[ORM\PrePersist]
    public function prePersist(): void
    {
        $this->createdAt = new \DateTimeImmutable();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getClient(): ?string
    {
        return $this->client;
    }

    public function setClient(string $client): static
    {
        $this->client = $client;

        return $this;
    }

    public function getReservation(): ?string
    {
        return $this->reservation;
    }

    public function setReservation(string $reservation): static
    {
        $this->reservation = $reservation;

        return $this;
    }

    public function getPriceHT(): ?float
    {
        return $this->priceHT;
    }

    public function setPriceHT(float $priceHT): static
    {
        $this->priceHT = $priceHT;

        return $this;
    }

    public function getPriceTTC(): ?float
    {
        return $this->PriceTTC;
    }

    public function setPriceTTC(float $PriceTTC): static
    {
        $this->PriceTTC = $PriceTTC;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function __toString(): string
    {
        return $this->id;
    }
}

templates/pdf/invoice_template.html.twig
{# templates/invoice_template.html.twig #}
<!DOCTYPE html>
<html>
<head>
    <title>Facture Invoice</title>
    <!-- Add your CSS styles here -->
    <style>
        /* Example styles */
        body {
            font-family: Arial, sans-serif;
        }
        .invoice {
            border: 1px solid #ccc;
            padding: 10px;
        }
        .invoice-title {
            font-size: 20px;
            font-weight: bold;
            text-align: center;
            margin-bottom: 20px;
        }
        .invoice-item {
            margin-bottom: 10px;
        }
        .invoice-item label {
            font-weight: bold;
        }
    </style>
</head>
<body>
    <div class="invoice">
        <div class="invoice-title">Facture Invoice</div>
        <div class="invoice-details">
            <div class="invoice-item">
                {# <label>Numéro de facture:</label> {{ invoice.id }} #}
            </div>
            <div class="invoice-item">
                {# <label>Date de création:</label> {{ invoice.createdAt|date('d/m/Y') }} #}
            </div>
            <div class="invoice-item">
                {# <label>Numéro de Réservation :</label> {{ invoice.reservation}} #}
            {% if reservation %}

            <div class="invoice-item">
                <label>Client:</label> {{ reservation.client.firstName }} {{ reservation.client.lastName }}
            </div>

            <div class="invoice-item">
                <label>Addresse de départ:</label> {{ reservation.depAddress }}
            </div>
            <div class="invoice-item">
                <label>Destination:</label> {{ reservation.destination }}
            </div>
            
            {% endif %}
            
           
            <div class="invoice-item">
                {# <label>Prix HT:</label> {{ invoice.priceHT //100 }} $
                <label>Prix TTC:</label> {{ invoice.priceTTC //100}}$ #}


            </div>
            <!-- Add more invoice details as needed -->
        </div>
    </div>
</body>
</html>